### ISSUE TITLE
Expose OUI Nonce

### ISSUE THREAD

**Issue by lthiery** [helium/blockchain-etl#124]
OUI nonce is needed when submitting OUI update (routing) transactions.

**Comment by madninja** [comment]
The `/v1/ouis` endpoint and `/v1/ouis/last` endpoint will need to be changed to expose the _active_ OUIs instead of just the transactions that created them. That will then also return the proper data for the oui post routing_v1 changes. 

In the meantime you can get the last oui (-1) from the `/v1/ouis/last` route, but expect the returned data to change over time to represent the current active endpoint (so not -1) in the near future

**Comment by madninja** [comment]
Fixed by #131  and https://github.com/helium/blockchain-http/pull/200
